# NUMPY INDEXING AND SELECTION

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)               # setting up an array

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]                           # getting values from array using index

8

In [7]:
arr[1:5]                        # using slicing

array([1, 2, 3, 4])

In [8]:
arr[:6]                         # calling values from beginning

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[:]                       # calling all values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[5:]                     # getting values till end

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# python has ability to broadcast

In [12]:
arr[0:5] = 100             # sets first 5 values equal to 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
slice_of_arr = arr[0:6]

In [28]:
slice_of_arr                     #  getting a slice of array

array([0, 1, 2, 3, 4, 5])

In [29]:
slice_of_arr[:] = 99

In [30]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [31]:
arr                                # changes not only slice but also whole array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
arr_copy =  arr.copy()

In [36]:
arr_copy                          # producing a numpy  array copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [37]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [38]:
arr_copy[:] = 100                # applying broadcasting

In [39]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [40]:
arr                            # orignal array remains same

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
# applying broadcasting to 2D array

In [42]:
arr_2D = np.array([[10,15,20],[25,30,35],[40,45,50]])           # print a 2D array

In [43]:
arr_2D

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [44]:
# format 1 for using 2D array indexing

In [50]:
arr_2D[2]                                                   # assesing values in nested list

array([40, 45, 50])

In [51]:
arr_2D[1][2]

35

In [ ]:
# format 2 for using 2D array indexing and assesing values

In [56]:
arr_2D[1,1]                                             # 00  01  02
                                                        # 10  11  12
                                                        # 20  21  22

30

In [57]:
arr_2D[:2,1:]                                                      # getting top right corner

array([[15, 20],
       [30, 35]])

In [ ]:
# grab everything (:) upto row 2  :2, 
# grab column 1 onwards 1:    [column:row+1]

In [64]:
  # get array of boolean vaues

In [65]:
arr = np.arange(0,11) 

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [72]:
bool_arr = arr >5

In [73]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [70]:
# conditional selection

In [74]:
arr[bool_arr]                        # gives value only where values are True

array([ 6,  7,  8,  9, 10])

In [75]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [76]:
arr[arr<3]

array([0, 1, 2])

In [77]:
arr_2D = np.arange(50).reshape(5,10)

In [78]:
arr_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [86]:
arr_2D[1:3,3:5]

array([[13, 14],
       [23, 24]])