# Numpy is a linear algebra library for python.
# All libraries in pydata rely on Numpy.

# NUMPY ARRAYS


In [5]:
# Numpy arrays
my_list = [1,2,3]

In [3]:
import numpy as np

In [7]:
 array = np.array(my_list)

In [8]:
array

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)           # shorcut to print an array using "arange" by defining range(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)         # get all even numbers(multiples)

array([0, 2, 4, 6, 8])

In [17]:
np.zeros(3)              # arrays of zeros           

array([0., 0., 0.])

In [19]:
np.zeros((2,3))          # passing a tuple  2 rows 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2,2))         # arrays of ones

array([[1., 1.],
       [1., 1.]])

In [21]:
np.ones(4)            # 1D array

array([1., 1., 1., 1.])

In [22]:
np.linspace(0,5,10)   # 10 evenly spaced  point numbers  (1D array)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.eye(4)            # form an identity matrix 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5)    # random 1D array

array([0.23465938, 0.62234706, 0.27239996, 0.41054276, 0.85682096])

In [25]:
np.random.rand(5,4)  # random 2D array

array([[0.72294862, 0.67899133, 0.47053404, 0.30595714],
       [0.94996247, 0.69362368, 0.52769891, 0.97667767],
       [0.2500435 , 0.2377515 , 0.73665173, 0.60563341],
       [0.73593388, 0.48259124, 0.40901412, 0.37727213],
       [0.45912125, 0.13537485, 0.01925715, 0.7860416 ]])

In [26]:
np.random.randn(2)     # random values from standard normal distribution

array([-0.83391875, -2.72328503])

In [29]:
np.random.randint(1,100)   # randint(low, high=None, size=None, dtype='l') random no.between 1 to 100 inclusive of 1    
                           # and exclusive of 100
                           # Return random integers from `low` (inclusive) to `high` (exclusive)

36

In [30]:
np.random.randint(1,100,10) # random 10 integers b/w 1 to 100

array([49, 93, 22, 42, 31,  5, 52, 45, 76, 33])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)

In [40]:
ranarr

array([ 9, 15, 43, 38, 28, 14, 15, 39, 26, 26])

In [43]:
arr.reshape(5,5)            # reshapes array 5 *5 =25 <= size of arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr

array([ 9, 15, 43, 38, 28, 14, 15, 39, 26, 26])

In [45]:
ranarr.max()              # find max value of array

43

In [46]:
ranarr.min()              # find min value of array

9

In [47]:
ranarr.argmax()          # finding index value of  min 

2

In [48]:
ranarr.argmin()         # finding index value of min

0

In [49]:
arr.shape              #finding shape of array  (1D array)

(25,)

In [50]:
arr = arr.reshape(5,5)

In [51]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.shape              # 2D array

(5, 5)

In [53]:
arr.dtype             # gives the datatype

dtype('int32')

In [54]:
from numpy.random import randint          # shortcut to random function directly from nupmy

In [55]:
randint(2,10)

9