# NumPy Arrays

In [127]:
# these come in two flavours : vectors(1d array only) and matrices(2d array)
# shift+tab for object details

In [10]:
# create an object
# python list
my_list = [1,2,3]

In [11]:
my_list

[1, 2, 3]

In [12]:
import numpy as np

In [13]:
# casting list as an array
arr = np.array(my_list)

In [14]:
arr

array([1, 2, 3])

In [15]:
# for a 2d array or a matrix
# create a list
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
# cast list in an array
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# creating an array
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# for creating array of even numbers
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [21]:
#creating a vector array of all zeros
np.zeros(3)

array([0., 0., 0.])

In [22]:
# creating a matrix(all ones 1's) by passing a tuple
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# for getting evenly spaced numbers between start and stop integers
np.linspace(0,5,10)
# 10 represents no. of elements u want b/w 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
# creating identity matrix using numpy
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# creating a random array using random values
np.random.rand(2,2)

array([[0.01775386, 0.49007871],
       [0.22443361, 0.56399602]])

In [26]:
# getting values from normal distribution
np.random.randn(2,2)

array([[-1.44367378, -0.65002619],
       [-0.50868803,  0.34493362]])

In [27]:
# getting random integer
np.random.randint(1,100)

66

In [28]:
# if u want 10 random integers 
np.random.randint(1,100,10)

array([49, 71, 90, 88, 35, 47, 43, 76, 58, 12])

In [29]:
# reshaping an object list
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([23, 16, 12, 32, 45, 11, 28, 44, 31, 19])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
# finding max and min value in array
ranarr.max()

45

In [35]:
ranarr.min()

11

In [36]:
# to get index location of max and min value
ranarr.argmax()

4

In [37]:
ranarr.argmin()

5

In [38]:
# to know shape of vector
arr.shape
# answer implies that arr is a 1D vector

(25,)

In [39]:
arr = arr.reshape(5,5) # reshaping arr

In [40]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr.shape

(5, 5)

In [42]:
# tells about type of values in arr(matrix)
arr.dtype

dtype('int32')

In [43]:
from numpy.random import randint

In [44]:
# getting a random integer
randint(5,100)

61

In [45]:
# numpy selection and indexing
arr = np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# getting value at a particular index
arr[8]

8

In [48]:
# using SLICE NOTATION

arr[1:5]
# starting from 1 till 4 gives values at all indexes from 1 to 4

array([1, 2, 3, 4])

In [49]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [50]:
# start at a particular index till end
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
# numpy array is different from normal python array due to its ability of broadcast

arr[0:5] = 100
# this broadcasts 100(value)to first 5 indexes

In [52]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
arr[0:5]

array([100, 100, 100, 100, 100])

In [54]:
arr = np.arange(0,11)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
slice_of_array = arr[0:6]

In [57]:
slice_of_array 

array([0, 1, 2, 3, 4, 5])

In [58]:
slice_of_array[:] = 99

In [59]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [60]:
arr
# this shows that braodcasting has altered the orignal data as well

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
# using COPY METHOD so that the orignal data is not altered
arr_copy = arr.copy()

In [62]:
arr_copy[:] =100

In [63]:
# creating a 2d array
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [64]:
arr_2d
# 00 01 02
# 10 11 12
# 20 21 22

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [65]:
# indexing or addressing values
arr_2d[0][0]   # for single value

5

In [66]:
# indexing the entire row
arr_2d[0] 

array([ 5, 10, 15])

In [67]:
# second method
arr_2d[2,0]

35

In [68]:
# using Slice notation
arr_2d[:2 ,1:]

# call everything till row 2 , and then grab column 1 onwards

array([[10, 15],
       [25, 30]])

In [69]:
# breaking the above code as 
arr_2d[:2]

# take everything till row 2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [70]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [71]:
# Conditional selection
arr = np.arange(1,11)
# take all values from 1 to 10

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
# appliying comparision operators on the array to get boolean array
bool_arr =arr >5

In [80]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [81]:
arr[bool_arr]
# it returns array for corresponding True boolean values

array([ 6,  7,  8,  9, 10])

In [82]:
arr[arr<3]

array([1, 2])

In [83]:
arr = np.arange(50).reshape(5,10)

In [84]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [90]:
arr[1:3,3:5]
# [Rows ,Columns]

array([[13, 14],
       [23, 24]])

## Numpy Operations

#Array with Array operations
#Array with Scalars
#Universal Array Functions

In [106]:
arr = np.arange(0,11)

In [107]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
# adding two arrays on element by element basis

Add = arr +arr

In [97]:
Add

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [98]:
# Subtraction
sub = arr - arr

In [99]:
sub

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
# multiplication
mul = arr*arr

In [101]:
mul

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [103]:
# appliying scalar operations

arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [109]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [110]:
arr ** 2
# Squared

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [111]:
# Taking SQUARED ROOT of each element in array

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [112]:
# calculating the Exponential

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [115]:
# for MAXIMUM and MINIMUM

np.max(arr)


10

In [116]:
np.min(arr)

0

In [121]:
np.log(arr) 
# numpy issues a warning for infintiy answer

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Numpy Exercises

In [123]:
# Creating an array of all 5's
np.ones(10) *5 

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [124]:
#  creating an array of EVEN INTEGERS from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [128]:
# create an IDENTITY MATRIX of order 3 X 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
# generate random number between 0 and 1
np.random.rand(1)

array([0.04002296])

In [131]:
np.linspace(.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [137]:
mat = np.arange(1,26).reshape(5,5)

In [138]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [142]:
# get No. 20
mat[3:4,4:]

array([[20]])

In [148]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [151]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [153]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [154]:
# sum of all numbers
mat.sum()

325

In [155]:
# STANDARD DEVIATION

np.std(mat)

7.211102550927978

In [156]:
# Sum of all columns
mat.sum(axis=0)

array([55, 60, 65, 70, 75])